# Generated by Django 4.0 on 2021-12-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0002_alter_userprofile_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userPassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userContact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userEmail',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
